# Generated by Django 4.2.3 on 2023-08-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(unique=True)),
                ('message_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время начала')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='Время на выполнение(секундах)')),
                ('periodicity', models.PositiveIntegerField(verbose_name='Периодичность привычки в днях')),
                ('good_habit_sign', models.BooleanField(verbose_name='Полезность привычки')),
                ('reward', models.CharField(blank=True, max_length=50, null=True, verbose_name='Награда')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичность')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
